name: macOS Vagrant Development Build
on:
  push:
    branches: 'dev-macos-*'
  workflow_dispatch:

jobs:
  trigger-build:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Vagrant macOS Development Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Trigger Development Build
        run: ./.ci/dev-build "${BRANCH}" "${COMMIT_ID}" build-macos
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_ID: ${{ github.sha }}
