on:
  pull_request:
    branches:
      - main
    ignored-paths:
      - 'builtin/**'
      - 'cmd/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  unit-tests-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0', '3.1', '3.2', '3.3']
    name: Vagrant unit tests on Go (Ruby ${{ matrix.ruby }})
    steps:
      - name: Stubbed for skip
        run: "echo 'No testing required in changeset'"
