on:
  schedule:
    - cron: 30 4 * * *

jobs:
  trigger-nightly:
    if: github.repository == 'hashicorp/vagrant'
    name: Trigger Nightly Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Trigger Nightly Build
        run: ./.ci/nightly-build "${COMMIT_ID}"
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          COMMIT_ID: ${{ github.sha }}
